server:
  port: ${PORT:8080}

spring:

  datasource:
    platform: postgres
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/tourfirm}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:root}

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

    properties.hibernate.jdbc.lob.non_contextual_creation: true
